services:
  redis-master:
    image: 'redis:7-alpine'
    container_name: ${COMPOSE_PROJECT_NAME}_master
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"
    command: redis-server --requirepass ${REDIS_MASTER_PASS} --masterauth ${REDIS_MASTER_PASS}
    ports:
      - '${DC_REDIS_PORT:-6379}:6379'
    volumes:
      - ./data:/data
    environment:
      - REDIS_REPLICATION_MODE=master
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
